# Generated by Django 4.2.13 on 2024-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2015-06-27'),
            preserve_default=False,
        ),
    ]
